version: "3.1"

services:
  api:
    build: .
    volumes:
      - ./:/home/node/api
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: diet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 90tJ3W2CCU10KOdbTauJdx98ja1L5f
    ports:
      - 5432:5432

volumes:
  postgres_data:
